cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-interchain-security-module-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace = true
solana-program.workspace = true
spl-discriminator.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
